// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpmqzkhmbkumfaeohikr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwbXF6a2htYmt1bWZhZW9oaWtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NzIxNDksImV4cCI6MjA2ODU0ODE0OX0.MZbmO3IgemQ1UsYzSThiOUmFJ5jWkORiIKogwH1GKxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});